[phases.setup]
nixPkgs = ["python311", "pip", "nodejs_22", "npm"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm ci"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && gunicorn music_streaming.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"