# Generated by Django 5.2.3 on 2025-06-30 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='設置鍵')),
                ('value', models.TextField(verbose_name='設置值')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '系統設置',
                'verbose_name_plural': '系統設置',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='JamendoAPICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='緩存鍵')),
                ('response_data', models.JSONField(verbose_name='響應數據')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('expires_at', models.DateTimeField(verbose_name='過期時間')),
            ],
            options={
                'verbose_name': 'API 緩存',
                'verbose_name_plural': 'API 緩存',
                'db_table': 'jamendo_api_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='jamendo_api_cache_k_ab1b4e_idx'), models.Index(fields=['expires_at'], name='jamendo_api_expires_5f7b09_idx')],
            },
        ),
        migrations.CreateModel(
            name='JamendoTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jamendo_id', models.IntegerField(unique=True, verbose_name='Jamendo ID')),
                ('name', models.CharField(max_length=500, verbose_name='歌曲名稱')),
                ('artist_name', models.CharField(max_length=200, verbose_name='藝人名稱')),
                ('artist_id', models.IntegerField(verbose_name='藝人 ID')),
                ('album_name', models.CharField(blank=True, max_length=200, verbose_name='專輯名稱')),
                ('album_id', models.IntegerField(blank=True, null=True, verbose_name='專輯 ID')),
                ('duration', models.IntegerField(verbose_name='時長(秒)')),
                ('position', models.IntegerField(default=1, verbose_name='專輯中的位置')),
                ('releasedate', models.DateField(blank=True, null=True, verbose_name='發行日期')),
                ('audio', models.URLField(verbose_name='音頻串流 URL')),
                ('audiodownload', models.URLField(verbose_name='音頻下載 URL')),
                ('image', models.URLField(blank=True, verbose_name='歌曲封面')),
                ('album_image', models.URLField(blank=True, verbose_name='專輯封面')),
                ('musicinfo_tags_genres', models.TextField(blank=True, help_text='JSON 格式存儲的曲風標籤列表', verbose_name='曲風標籤')),
                ('musicinfo_tags_instruments', models.TextField(blank=True, help_text='JSON 格式存儲的樂器標籤列表', verbose_name='樂器標籤')),
                ('musicinfo_tags_vartags', models.TextField(blank=True, help_text='JSON 格式存儲的其他標籤列表', verbose_name='其他標籤')),
                ('stats_rate', models.FloatField(default=0.0, verbose_name='評分')),
                ('stats_downloads_total', models.IntegerField(default=0, verbose_name='下載次數')),
                ('stats_playlisted', models.IntegerField(default=0, verbose_name='收藏次數')),
                ('cached_at', models.DateTimeField(auto_now=True, verbose_name='緩存時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
            ],
            options={
                'verbose_name': 'Jamendo 音軌',
                'verbose_name_plural': 'Jamendo 音軌',
                'db_table': 'jamendo_tracks',
                'ordering': ['-stats_rate', '-stats_downloads_total'],
                'indexes': [models.Index(fields=['jamendo_id'], name='jamendo_tra_jamendo_5814e1_idx'), models.Index(fields=['artist_name'], name='jamendo_tra_artist__150a17_idx'), models.Index(fields=['album_name'], name='jamendo_tra_album_n_ef1a80_idx'), models.Index(fields=['stats_rate'], name='jamendo_tra_stats_r_67d213_idx'), models.Index(fields=['cached_at'], name='jamendo_tra_cached__33c5c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserListeningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_listening_time', models.BigIntegerField(default=0, verbose_name='總聽歌時間(秒)')),
                ('total_tracks_played', models.IntegerField(default=0, verbose_name='播放歌曲總數')),
                ('total_tracks_completed', models.IntegerField(default=0, verbose_name='完整播放歌曲數')),
                ('favorite_genre', models.CharField(blank=True, max_length=100, verbose_name='最喜愛曲風')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('most_played_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jamendo.jamendotrack', verbose_name='最常播放的歌曲')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listening_stats', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶聽歌統計',
                'verbose_name_plural': '用戶聽歌統計',
                'db_table': 'user_listening_stats',
            },
        ),
        migrations.CreateModel(
            name='UserPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='播放列表名稱')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶播放列表',
                'verbose_name_plural': '用戶播放列表',
                'db_table': 'user_playlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='位置')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加時間')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='jamendo.userplaylist', verbose_name='播放列表')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jamendo.jamendotrack', verbose_name='音軌')),
            ],
            options={
                'verbose_name': '播放列表音軌',
                'verbose_name_plural': '播放列表音軌',
                'db_table': 'user_playlist_tracks',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏時間')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jamendo.jamendotrack', verbose_name='音軌')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶收藏',
                'verbose_name_plural': '用戶收藏',
                'db_table': 'user_favorite_tracks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_favori_user_id_edbeee_idx'), models.Index(fields=['track'], name='user_favori_track_i_297e41_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.CreateModel(
            name='UserPlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='用於匿名用戶追蹤', max_length=100, verbose_name='會話 ID')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='播放時間')),
                ('duration_played', models.IntegerField(default=0, verbose_name='播放時長(秒)')),
                ('completed', models.BooleanField(default=False, verbose_name='是否播放完整')),
                ('user_agent', models.TextField(blank=True, verbose_name='用戶代理')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to='jamendo.jamendotrack', verbose_name='音軌')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '播放歷史',
                'verbose_name_plural': '播放歷史',
                'db_table': 'user_play_history',
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', 'played_at'], name='user_play_h_user_id_584772_idx'), models.Index(fields=['session_id', 'played_at'], name='user_play_h_session_612509_idx'), models.Index(fields=['track', 'played_at'], name='user_play_h_track_i_aa789d_idx'), models.Index(fields=['played_at'], name='user_play_h_played__def115_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userplaylist',
            index=models.Index(fields=['user', 'updated_at'], name='user_playli_user_id_cad778_idx'),
        ),
        migrations.AddIndex(
            model_name='userplaylist',
            index=models.Index(fields=['is_public', 'updated_at'], name='user_playli_is_publ_d3ba20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userplaylist',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='userplaylisttrack',
            index=models.Index(fields=['playlist', 'position'], name='user_playli_playlis_20a498_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userplaylisttrack',
            unique_together={('playlist', 'track')},
        ),
    ]
